#ifndef _INCLUDE_STARS_H
#define _INCLUDE_STARS_H

/*
 * File generated by StormLink from SoftDisk:User/mcpp3/work/octree/texture_src/texture.fd
 * DO NOT EDIT
 * $VER: stars.rtx 1.0 (09-Mai-99)
 */
#ifdef __cplusplus
extern "C" {
#endif
#pragma amicall(TextureBase, 0x1e, texture_init())
#ifdef __cplusplus
};
#endif
#endif
