#ifndef _INCLUDE_BUMP_H
#define _INCLUDE_BUMP_H

/*
 * File generated by StormLink from SoftDisk:User/mcpp3/work/octree/texture_src/texture.fd
 * DO NOT EDIT
 * $VER: bump.rtx 1.0 (17-Okt-99)
 */
#ifdef __cplusplus
extern "C" {
#endif
#pragma amicall(TextureBase, 0x1e, texture_init())
#ifdef __cplusplus
};
#endif
#endif
