//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by scenario.rc
//
#define ID_STATUSBAR_OBJECT             1
#define ID_STATUSBAR_CAMERA             2
#define ID_STATUSBAR_COORDY             3
#define ID_STATUSBAR_COORDZ             4
#define ID_COORD_X                      6
#define ID_COORD_Y                      7
#define ID_COORD_Z                      8
#define IDS_ERRSTARTAPP                 10
#define IDS_ERRPREFSLOAD                12
#define IDS_ERRPREFSSAVE                13
#define IDS_ERRFAILEDRSI                14
#define IDS_ERRNOMEM                    15
#define IDS_ERRNOFILE                   16
#define IDS_ERRNOVIEWER                 17
#define IDS_ERRNOOBJSELECT              18
#define IDS_ERRNOCAMERA                 19
#define IDS_ERRNOPICNAME                20
#define IDS_ERRNOOUTPUT                 20
#define IDS_ERRNOTRACK                  21
#define IDS_ERRTRACKTOSELF              22
#define IDS_ERRLOADTEXTURE              23
#define IDS_ERRWRONGTEXTURE             24
#define IDD_ABOUTBOX                    100
#define ID_ABOUT_LINE1                  100
#define ID_RENDERBOX_LISTBOX            100
#define IDC_TREE                        100
#define IDD_FLARESET                    101
#define ID_ABOUT_LINE2                  101
#define ID_RENDERBOX_ELAPSED            101
#define IDR_POPUP_OBJECT                101
#define IDD_GRIDSIZE                    102
#define ID_ABOUT_LINE3                  102
#define ID_RENDERBOX_TIMELEFT           102
#define IDR_POPUP_WORLD                 102
#define IDD_TRANSFORM                   103
#define ID_RENDERBOX_ESTIMAT            103
#define IDR_POPUP_POINTLIGHT            103
#define IDD_COLOR                       104
#define IDR_POPUP_SPOTLIGHT             104
#define IDD_BRUSH                       105
#define IDR_POPUP_CAMERA                105
#define IDD_TEXTURE                     106
#define IDD_CAMERASET                   107
#define IDD_LIGHTSET                    108
#define IDD_PREFSET                     110
#define ID_PREFS_VIEWER                 110
#define ID_CUBE_X                       110
#define ID_SPHERE_RADIUS                110
#define ID_PLANE_X                      110
#define ID_TUBE_RADIUS                  110
#define ID_CONE_RADIUS                  110
#define ID_TORUS_RADIUS                 110
#define IDM_POPUP_ACTIVECAMERA          110
#define IDC_BRUSH_REPEAT                111
#define ID_CUBE_Y                       111
#define ID_SPHERE_DIVISIONS             111
#define ID_PLANE_Y                      111
#define ID_TUBE_HEIGHT                  111
#define ID_CONE_HEIGHT                  111
#define ID_TORUS_THICKNESS              111
#define IDD_RENDERBOX                   112
#define IDC_BRUSH_MIRROR                112
#define ID_PREFS_PROJECT                112
#define ID_CUBE_Z                       112
#define ID_SPHERE_SLICES                112
#define ID_PLANE_Z                      112
#define ID_TUBE_DIVISIONS               112
#define ID_CONE_DIVISIONS               112
#define ID_TORUS_DIVISIONS              112
#define IDC_BRUSH_SOFT                  113
#define ID_PREFS_PROJECTBUT             113
#define ID_PLANE_XDIV                   113
#define ID_TUBE_SLICES                  113
#define ID_CONE_SLICES                  113
#define ID_TORUS_SLICES                 113
#define ID_PREFS_OBJECT                 114
#define ID_PLANE_ZDIV                   114
#define ID_TUBE_CLOSETOP                114
#define ID_CONE_CLOSEBOTTOM             114
#define IDD_BROWSER                     115
#define ID_PREFS_OBJECTBUT              115
#define ID_TUBE_CLOSEBOTTOM             115
#define IDD_CUBE                        116
#define ID_PREFS_BRUSH                  116
#define IDD_SPHERE                      117
#define ID_PREFS_BRUSHBUT               117
#define ID_PREFS_MATERIAL               118
#define IDD_PLANE                       118
#define ID_PREFS_MATERIALBUT            119
#define IDD_TUBE                        119
#define ID_PREFS_TEXTURE                120
#define IDD_CONE                        120
#define IDC_BRUSH_ADD                   120
#define ID_PREFS_TEXTUREBUT             121
#define IDD_TORUS                       121
#define IDC_BRUSH_REMOVE                121
#define IDD_FLAGSET                     122
#define IDC_BRUSH_UP                    122
#define ID_PREFS_VIEWERBUT              122
#define IDD_MESHSET                     123
#define IDC_BRUSH_DOWN                  123
#define ID_PREFS_LIGHTS                 123
#define IDD_STARSET                     124
#define IDC_COLOR_DIFFUSE               124
#define IDC_BRUSH_NAME                  124
#define ID_PREFS_LIGHTSBUT              124
#define IDC_COLOR_SPECULAR              125
#define IDD_PICTURE                     126
#define IDC_COLOR_TRANSPAR              126
#define IDC_COLOR_REFLECT               127
#define IDD_MISCSET                     128
#define IDC_COLOR_AMBIENT               128
#define IDR_MAINFRAME                   128
#define IDB_BITMAP_UP                   129
#define IDC_COLOR_DIFFTRANS             129
#define IDB_BITMAP_DOWN                 130
#define IDC_COLOR_SPECTRANS             130
#define IDB_BITMAP_ADD                  131
#define IDC_COLOR_TRANSLUC              131
#define IDB_BITMAP_REMOVE               132
#define IDC_COLOR_SPECEXP               132
#define IDR_MATERIAL                    133
#define IDC_COLOR_TRANSEXP              133
#define IDC_COLOR_REFRACT               134
#define IDC_COLOR_FOGLENGTH             135
#define IDC_COLOR_BRIGHT                136
#define IDD_CSGSET                      136
#define IDD_PRIMSET                     137
#define IDB_BROWSER                     138
#define IDD_OBJSEL                      139
#define ID_FILE_RENDER                  140
#define IDR_MATERIAL_OUTSIDE            140
#define IDD_RENAME                      141
#define IDD_RENDER_RESO                 142
#define IDD_RENDER_MISC                 144
#define IDD_RENDER_OUTPUT               145
#define IDD_GLOBAL_ENV                  146
#define IDD_GLOBAL_MISC                 149
#define IDM_CUT                         150
#define IDB_BITMAP_FILE                 150
#define IDM_COPY                        151
#define IDB_BITMAP_FOLDER               151
#define IDM_PASTE                       152
#define IDB_BITMAP_VIEW                 152
#define IDM_DELETE                      153
#define IDB_BITMAP_BROWSE               153
#define IDC_TEXTURE_ADD                 154
#define IDM_MOVEOBJECT                  154
#define IDD_COLORMANIP                  154
#define IDC_TEXTURE_REMOVE              155
#define IDM_ROTATEOBJECT                155
#define IDB_BITMAP_NAME                 155
#define IDC_TEXTURE_UP                  156
#define IDM_SIZEOBJECT                  156
#define IDD_COLORSET                    156
#define IDC_TEXTURE_DOWN                157
#define IDM_MOVEWORLD                   157
#define ID_GRIDSIZE_SIZE                158
#define IDM_ROTATEWORLD                 158
#define IDC_TEXTURE_NAME                158
#define IDM_ZOOMWORLD                   159
#define IDM_SELECT_ALL                  160
#define ID_CAMERASET_FOCAL              161
#define IDM_DESELECT_ALL                161
#define ID_CAMERASET_APERT              162
#define IDM_SELECT_NEXT                 162
#define ID_CAMERASET_LISTBOX            163
#define IDM_SELECT_PREV                 163
#define ID_CAMERASET_FOVH               164
#define IDM_FILTERX                     164
#define ID_CAMERASET_FOVV               165
#define IDM_FILTERY                     165
#define ID_CAMERASET_FROMRES            166
#define IDM_FILTERZ                     166
#define ID_LIGHTSET_TRACKTEXT           168
#define ID_LIGHTSET_COLOR               170
#define ID_LIGHTSET_RADIUS              171
#define ID_LIGHTSET_FALLOFF             172
#define ID_LIGHTSET_ANGLE               173
#define ID_LIGHTSET_ANGLETEXT           174
#define ID_LIGHTSET_SHADOW              175
#define ID_MESHSET_FILE                 176
#define ID_MESHSET_FILEBUT              177
#define ID_MESHSET_APPLY                178
#define ID_TRANSFORM_NAME               179
#define ID_TRANSFORM_POSX               180
#define ID_TRANSFORM_POSY               181
#define ID_TRANSFORM_POSZ               182
#define ID_TRANSFORM_ALIGNX             183
#define ID_TRANSFORM_ALIGNY             184
#define ID_TRANSFORM_ALIGNZ             185
#define ID_TRANSFORM_SIZEX              186
#define ID_TRANSFORM_SIZEY              187
#define ID_TRANSFORM_SIZEZ              188
#define ID_GLOBAL_BACKCOLOR             190
#define ID_GLOBAL_AMBIENTCOLOR          191
#define ID_GLOBAL_BACKDROP              192
#define ID_GLOBAL_BACKDROPBUT           193
#define ID_GLOBAL_REFLECTION            194
#define ID_GLOBAL_REFLECTIONBUT         195
#define ID_GLOBAL_VIEW_BACKDROP         196
#define ID_GLOBAL_VIEW_REFLECT          197
#define ID_GLOBAL_ANTI                  198
#define ID_GLOBAL_CONTRAST              200
#define IDM_REDRAW                      200
#define ID_GLOBAL_FILTERWIDTH           201
#define IDM_FOCUSOBJECT                 201
#define ID_COLOR_RING                   201
#define ID_STAR_RINGCOLOR               201
#define ID_GLOBAL_FOGCOLOR              202
#define IDM_ZOOM_IN                     202
#define ID_GLOBAL_FOGLENGTH             203
#define IDM_ZOOM_OUT                    203
#define ID_GLOBAL_FOGHEIGHT             204
#define IDM_ZOOM_FIT                    204
#define ID_GLOBAL_MOTION                205
#define IDM_FRONT                       205
#define IDM_RIGHT                       206
#define ID_GLOBAL_SOFT                  207
#define IDM_TOP                         207
#define IDM_PERSPECTIVE                 208
#define ID_GLOBAL_RANDJIT               209
#define IDM_4T                          209
#define ID_RENDER_RESX                  210
#define IDM_CAMERAVIEW                  210
#define ID_RENDER_RESY                  211
#define IDM_RENDER_SETTINGS             211
#define ID_RENDER_XMIN                  212
#define IDM_RENDER                      212
#define ID_RENDER_YMIN                  213
#define IDM_GRID                        213
#define ID_RENDER_XMAX                  214
#define IDM_GRIDSNAP                    214
#define ID_RENDER_YMAX                  215
#define IDM_GRIDSIZE                    215
#define ID_RENDER_ENABLE                216
#define IDM_SHOWCOORDS                  216
#define IDM_SHOWNAMES                   217
#define ID_RENDER_QUICK                 218
#define IDM_SHOWBRUSHES                 218
#define ID_RENDER_OCDEPTH               219
#define IDM_SHOWTEXTURES                219
#define ID_RENDER_OCDEPTHCTRL           220
#define IDM_GLOBALSETTINGS              220
#define ID_RENDER_FILENAME              221
#define IDM_BOUNDING                    221
#define ID_RENDER_FILENAMEBUT           222
#define IDM_WIRE                        222
#define ID_RENDER_VIEW_FILE             223
#define IDM_SOLID                       223
#define ID_RENDER_FORMAT                224
#define ID_RENDER_SHOW                  225
#define IDM_SURFACE                     400
#define IDM_SETTINGS                    401
#define IDM_LOADOBJECT                  402
#define IDM_SPHERE                      404
#define IDM_PLANE                       405
#define IDM_POINTLIGHT                  406
#define IDM_SPOTLIGHT                   407
#define IDM_CAMERA                      408
#define IDM_MAXIS                       409
#define IDM_MCUBE                       410
#define IDM_MSPHERE                     411
#define IDM_MPLANE                      412
#define IDM_MTUBE                       413
#define IDM_MCONE                       414
#define IDM_MTORUS                      415
#define IDM_ACTIVECAMERA                416
#define IDM_BROWSE                      417
#define IDM_PREFS                       501
#define IDM_LOADPREFS                   502
#define IDM_SAVEPREFS                   503
#define IDM_CONTENT                     600
#define ID_FLARES_DRAWAREA              1002
#define ID_FLARES_COLOR                 1007
#define ID_FLARES_FUNCTION              1008
#define IDM_CENTERVIEW                  1012
#define ID_FLARES_ADD                   1012
#define ID_FLARES_REMOVE                1013
#define ID_LIGHTSET_FLARES              1014
#define ID_LIGHTSET_STAR                1015
#define ID_FLARES_TILTTEXT              1019
#define ID_STAR_HALOENABLE              1023
#define ID_FLARES_SLE_RADIUS            1024
#define ID_FLARES_STYLES                1025
#define ID_FLARES_SLE_POS               1026
#define ID_STAR_ENABLE                  1027
#define ID_FLARES_SLE_TILT              1027
#define ID_STAR_DRAWAREA                1028
#define ID_FLARES_SLE_NUMBER            1028
#define ID_STAR_RANDOM                  1030
#define ID_STAR_SLE_RADIUS              1031
#define ID_FLARES_SLB_RADIUS            1032
#define ID_STAR_SLE_SPIKES              1032
#define ID_FLARES_SLB_POS               1033
#define ID_STAR_SLE_RANGE               1033
#define ID_FLARES_SLB_TILT              1034
#define ID_STAR_WIDTH                   1034
#define ID_STAR_NOISE                   1034
#define ID_STAR_SLB_SPIKES              1035
#define ID_FLARES_SLB_NUMBER            1035
#define ID_STAR_SLB_RANGE               1036
#define ID_STAR_SLB_HRADIUS             1037
#define ID_STAR_SLE_HRADIUS             1038
#define ID_STAR_SLB_HIRADIUS            1039
#define ID_STAR_SLE_HIRADIUS            1040
#define ID_STAR_SLB_RADIUS              1041
#define ID_RENDERBOX_SHOW               1042
#define ID_STAR_BRIGHTNESS              1042
#define ID_STAR_SLB_TILT                1043
#define ID_FLAGS_SHOWCOORD              1044
#define ID_STAR_SLE_TILT                1044
#define ID_UNDO_SLB_MEMORY              1045
#define ID_UNDO_SLE_MEMORY              1046
#define ID_RENDER_MINOBJ                1047
#define ID_MISC_SLB_JPEG                1047
#define ID_TRANSFORM_TRACK              1048
#define ID_MISC_SLE_JPEG                1048
#define ID_TRANSFORM_TRACKBUT           1049
#define ID_RENDERBOX_PROGRESS           1050
#define ID_RENDERBOX_PERCENT            1051
#define ID_CAMERASET_FOCUS              1052
#define ID_CAMERASET_FASTDOF            1053
#define ID_LIGHTSET_FROMTRACK           1054
#define ID_CAMERASET_HIDDENAREA         1054
#define ID_LIGHTSET_SLB_SDWSIZE         1055
#define ID_CAMERASET_ACCELERATE         1055
#define ID_LIGHTSET_SLE_SDWSIZE         1056
#define ID_RENDER_COMBOBOX              1058
#define IDC_TEXTURE_PARAMETERS          1060
#define IDC_TEXTURE_VALUE               1062
#define IDC_BRUSH_TYPES                 1063
#define IDC_BRUSH_WRAP                  1064
#define IDC_BRUSH_NAMES                 1065
#define IDC_TEXTURE_NAMES               1066
#define IDC_TRANSFORM_INVERTED          1070
#define IDC_GLOBAL_ENABLEBACKDROP       1071
#define IDC_GLOBAL_ENABLEREFLMAP        1072
#define IDC_CSG_TYPE                    1072
#define IDC_PRIMSET_CLOSEDTOP           1074
#define IDC_PRIMSET_CLOSEDBOTTOM        1075
#define IDC_PRIMSET_SORCALC             1077
#define IDC_GLOBAL_MOTIONSPIN           1078
#define IDC_OBJSEL_LIST                 1079
#define IDC_RENAME                      1080
#define IDC_COLOR_SPECEXPSPIN           1083
#define IDC_COLOR_TRANSEXPSPIN          1085
#define IDC_COLOR_REFRACTSPIN           1086
#define IDC_COLOR_FOGLENGTHSPIN         1087
#define IDC_COLOR_TRANSLUCSPIN          1088
#define IDC_TEXTURE_VALUESPIN           1089
#define IDC_COLMANIP_R                  1094
#define IDC_COLMANIP_G                  1095
#define IDC_COLMANIP_B                  1096
#define ID_COLOR_STAR                   1098
#define ID_STAR_COLOR                   1098
#define IDC_RADIO1                      1100
#define ID_COLORLIST                    1101
#define ID_COLORBUTTON                  1102
#define ID_TRANS_POSLOC                 1103
#define ID_TRANS_ALGLOC                 1104
#define ID_LIGHTSET_LOAD                1104
#define ID_TRANS_SIZLOC                 1105
#define ID_LIGHTSET_SAVE                1105
#define ID_STATUSBAR_OBJECTTXT          5000
#define ID_STATUSBAR_CAMERATXT          5001
#define ID_STATUSBAR_COORDX             5002
#define IDM_CAMTOVIEW                   40001
#define IDM_GROUP                       40004
#define IDM_UNGROUP                     40005
#define IDM_SAVEOBJECT                  40008
#define IDM_UNDO                        40010
#define IDM_BOX                         40011
#define IDM_REDO                        40012
#define IDM_TOSCENE                     40013
#define IDM_CONE                        40014
#define IDM_CYLINDER                    40015
#define IDM_CSG                         40016
#define IDM_SOR                         40017
#define IDM_MATERIAL_NEW                40019
#define IDM_MATERIAL_LOAD               40020
#define ID_BUTTON40021                  40021
#define ID_BUTTON40022                  40022
#define ID_BUTTON40023                  40023
#define ID_BUTTON40024                  40024
#define ID_BUTTON40025                  40025
#define ID_BUTTON40026                  40026
#define ID_BUTTON40027                  40027
#define ID_BUTTON40028                  40028
#define ID_BUTTON40029                  40029
#define ID_BUTTON40030                  40030
#define ID_BUTTON40031                  40031
#define ID_BUTTON40032                  40032
#define ID_BUTTON40033                  40033
#define ID_BUTTON40034                  40034
#define ID_BUTTON40035                  40035
#define ID_BUTTON40036                  40036
#define ID_BUTTON40037                  40037
#define ID_BUTTON40038                  40038
#define ID_BUTTON40039                  40039
#define ID_BUTTON40040                  40040
#define ID_BUTTON40041                  40041
#define IDM_SELECT                      40042
#define IDM_EDITPOINTS                  40043
#define IDM_ADDPOINTS                   40044
#define IDM_SETRENDERWINDOW             40045
#define IDM_MATERIAL_SAVE               40046
#define IDM_MATERIAL_ATTRIBUTES         40047
#define IDM_MATERIAL_DELETE             40048
#define IDM_MATERIAL_ASSIGN             40049
#define IDM_MATERIAL_LOADNEW            40051
#define IDM_MAT_MANAGER                 40052
#define IDM_BROWSERENABLE               40053
#define IDM_MATERIAL_ONOFF              40054
#define IDM_BROWSER_ONOFF               40055
#define IDM_MATERIAL_RENAME             40056
#define IDM_EDITEDGES                   40058
#define IDM_ADDFACES                    40061
#define IDM_ADDEDGES                    40063
#define IDM_EDITFACES                   40064
#define ID_BUTTON40065                  40065
#define IDM_MATERIAL_REMOVEUNUSED       40066
#define IDM_MATERIAL_REMOVEIDENTICAL    40067
#define IDM_FILTERSHIFTX                40070
#define IDM_FILTERSHIFTY                40071
#define IDM_FILTERSHIFTZ                40072
#define IDM_SHOWALL                     40073
#define IDM_SHOWCAMERAS                 40074
#define IDM_SHOWLIGHTS                  40075
#define IDM_SHOWMESHES                  40076
#define IDM_SHOWSHPERES                 40077
#define IDM_SHOWBOXES                   40078
#define IDM_SHOWCYLINDERS               40079
#define IDM_SHOWCONES                   40080
#define IDM_SHOWSORS                    40081
#define IDM_SHOWPLANES                  40082
#define IDM_SHOWCSG                     40083
#define IDM_SHOWSPHERES                 40084
#define ID_BUTTON40085                  40085
#define IDM_LOCAL                       40086
#define ID_BUTTON40091                  40091
#define ID_BUTTON40092                  40092
#define IDS_ERRNAME                     61403
#define IDS_DDV_MINFLOAT                61404
#define IDS_DDV_MINFLOATEXC             61405
#define IDS_DDV_MINMAXFLOATEXC          61406
#define IDS_ERRNOTASSIGNED              61407
#define IDS_ERR_PLATFORM                61408
#define IDS_ERRPICNAME                  61409

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         40093
#define _APS_NEXT_CONTROL_VALUE         1105
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
