#ifndef _INCLUDE_RAYSTORM_H
#define _INCLUDE_RAYSTORM_H

/*
 * File generated by StormLink from keyfile.fd
 * DO NOT EDIT
 * $VER: RayStorm.key 1.0 (12-Mai-99)
 */
#ifdef __cplusplus
extern "C" {
#endif
#pragma amicall(KeyfileBase, 0x1e, keyGetInfo())
#pragma amicall(KeyfileBase, 0x24, keyDecodeKeyfile1())
#pragma amicall(KeyfileBase, 0x2a, keyDecodeKeyfile2())
#pragma amicall(KeyfileBase, 0x30, keyWritePicture())
#ifdef __cplusplus
};
#endif
#endif
