#ifndef _INCLUDE_TERRAIN_H
#define _INCLUDE_TERRAIN_H

/*
 * File generated by StormLink from SoftDisk:User/mcpp3/work/octree/plugins/plugin.fd
 * DO NOT EDIT
 * $VER: terrain 2.31 (13-Jun-99)
 */
#ifdef __cplusplus
extern "C" {
#endif
#pragma amicall(PluginBase, 0x1e, plugin_init())
#ifdef __cplusplus
};
#endif
#endif
