scenario: animtree_class.o attrswindow_class.o box.o browsertree_class.o browser_class.o brush.o camera.o\
 color_class.o cone.o csg.o cylinder.o display.o dispwindow_class.o draw_class.o errors.o flares.o float_class.o\
 globals.o globalwindow_class.o iff_util.o light.o list.o mainwindow_class.o materialitem_class.o material_class.o\
 mesh.o meshaddwindow_class.o modeler.o mouse.o msghandler_class.o MUIutility.o numreq_class.o object.o\
 objhand.o plane.o prefs.o prefswindow_class.o preview.o project.o renderwindow_class.o render_class.o\
 requview_class.o sci.o settings_class.o slider_class.o sor.o sphere.o star.o statewindow_class.o subtask.o\
 surface.o texture.o undo.o utility.o view.o
	mcppc animtree_class.o attrswindow_class.o box.o browsertree_class.o browser_class.o brush.o camera.o\
 color_class.o cone.o csg.o cylinder.o display.o dispwindow_class.o draw_class.o errors.o flares.o float_class.o\
 globals.o globalwindow_class.o iff_util.o light.o list.o mainwindow_class.o materialitem_class.o material_class.o\
 mesh.o meshaddwindow_class.o modeler.o mouse.o msghandler_class.o MUIutility.o numreq_class.o object.o\
 objhand.o plane.o prefs.o prefswindow_class.o preview.o project.o renderwindow_class.o render_class.o\
 requview_class.o sci.o settings_class.o slider_class.o sor.o sphere.o star.o statewindow_class.o subtask.o\
 surface.o texture.o undo.o utility.o view.o -o scenario -gs -l amiga -l ray:lib_vecmath/maxon881/vecmath.lib

animtree_class.o: animtree_class.cpp animtree_class.h color.h display.h iff_util.h list.h MUIdefs.h MUIutility.h\
 object.h popup_menu.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c animtree_class.cpp

attrswindow_class.o: attrswindow_class.cpp attrswindow_class.h brush.h camera.h color.h display.h iff_util.h list.h\
 msghandler_class.h MUIdefs.h MUIutility.h object.h popup_menu.h prefs.h preview.h render_class.h sci.h\
 subtask.h surface.h texture.h typedefs.h undo.h utility.h vecmath.h view.h
	mcppc -c attrswindow_class.cpp

box.o: box.cpp box.h brush.h camera.h color.h display.h iff_util.h list.h MUIdefs.h object.h popup_menu.h\
 project.h rscn.h sci.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c box.cpp

browsertree_class.o: browsertree_class.cpp browsertree_class.h camera.h color.h csg.h display.h iff_util.h list.h\
 MUIdefs.h MUIutility.h object.h popup_menu.h prefs.h sci.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c browsertree_class.cpp

browser_class.o: browsertree_class.h browser_class.cpp browser_class.h color.h display.h iff_util.h list.h MUIdefs.h\
 MUIutility.h object.h popup_menu.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c browser_class.cpp

brush.o: brush.cpp brush.h color.h display.h iff_util.h list.h MUIdefs.h object.h popup_menu.h prefs.h\
 project.h rscn.h surface.h typedefs.h undo.h utility.h vecmath.h view.h
	mcppc -c brush.cpp

camera.o: camera.cpp camera.h color.h display.h globals.h iff_util.h list.h MUIdefs.h object.h popup_menu.h\
 project.h rscn.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c camera.cpp

color_class.o: color.h color_class.cpp color_class.h display.h iff_util.h list.h MUIdefs.h MUIutility.h object.h\
 popup_menu.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c color_class.cpp

cone.o: brush.h camera.h color.h cone.cpp cone.h display.h iff_util.h list.h magic.h MUIdefs.h object.h\
 popup_menu.h project.h rscn.h sci.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c cone.cpp

csg.o: color.h csg.cpp csg.h display.h iff_util.h list.h MUIdefs.h object.h popup_menu.h project.h\
 rscn.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c csg.cpp

cylinder.o: brush.h camera.h color.h cylinder.cpp cylinder.h display.h iff_util.h list.h magic.h MUIdefs.h\
 object.h popup_menu.h project.h rscn.h sci.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c cylinder.cpp

display.o: camera.h color.h display.cpp display.h errors.h gfx2d.h globals.h iff_util.h list.h magic.h\
 mainwindow_class.h MUIdefs.h object.h popup_menu.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c display.cpp

dispwindow_class.o: color.h display.h dispwindow_class.cpp dispwindow_class.h globals.h iff_util.h list.h MUIdefs.h\
 MUIutility.h object.h popup_menu.h preview.h render_class.h subtask.h surface.h texture.h typedefs.h\
 undo.h vecmath.h view.h
	mcppc -c dispwindow_class.cpp

draw_class.o: camera.h color.h cone.h csg.h display.h draw_class.cpp draw_class.h gfx2d.h iff_util.h light.h\
 list.h mainwindow_class.h mesh.h mouse.h MUIdefs.h MUIutility.h object.h popup_menu.h prefs.h project.h\
 sci.h settings_class.h surface.h typedefs.h undo.h utility.h vecmath.h view.h
	mcppc -c draw_class.cpp

errors.o: errors.cpp
	mcppc -c errors.cpp

flares.o: color.h display.h flares.cpp flares.h gfx2d.h iff_util.h light.h list.h MUIdefs.h object.h\
 popup_menu.h rscn.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c flares.cpp

float_class.o: color.h display.h float_class.cpp float_class.h iff_util.h list.h MUIdefs.h MUIutility.h object.h\
 popup_menu.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c float_class.cpp

globals.o: color.h globals.cpp globals.h typedefs.h
	mcppc -c globals.cpp

globalwindow_class.o: color.h display.h globals.h globalwindow_class.cpp globalwindow_class.h iff_util.h list.h MUIdefs.h\
 MUIutility.h object.h popup_menu.h prefs.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c globalwindow_class.cpp

iff_util.o: iff_util.cpp iff_util.h
	mcppc -c iff_util.cpp

light.o: camera.h color.h display.h flares.h iff_util.h light.cpp light.h list.h MUIdefs.h object.h\
 popup_menu.h project.h rscn.h star.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c light.cpp

list.o: list.cpp list.h typedefs.h
	mcppc -c list.cpp

mainwindow_class.o: animtree_class.h browsertree_class.h browser_class.h camera.h color.h display.h globals.h iff_util.h\
 list.h mainwindow_class.cpp mainwindow_class.h mesh.h meshaddwindow_class.h MUIdefs.h MUIutility.h object.h\
 picload.h popup_menu.h prefs.h project.h ray:keyfile/keyfile_lib.h sci.h surface.h typedefs.h undo.h\
 utility.h vecmath.h view.h
	mcppc -c mainwindow_class.cpp

materialitem_class.o: camera.h color.h display.h iff_util.h list.h materialitem_class.cpp materialitem_class.h msghandler_class.h\
 MUIdefs.h MUIutility.h object.h popup_menu.h preview.h render_class.h sci.h subtask.h surface.h texture.h\
 typedefs.h undo.h vecmath.h view.h
	mcppc -c materialitem_class.cpp

material_class.o: camera.h color.h display.h iff_util.h list.h materialitem_class.h material_class.cpp material_class.h\
 MUIdefs.h MUIutility.h object.h popup_menu.h preview.h sci.h subtask.h surface.h texture.h typedefs.h\
 undo.h vecmath.h view.h
	mcppc -c material_class.cpp

mesh.o: brush.h camera.h color.h display.h errors.h gfx2d.h iff_util.h list.h magic.h mesh.cpp mesh.h\
 mouse.h MUIdefs.h object.h popup_menu.h prefs.h project.h rscn.h sci.h surface.h typedefs.h undo.h utility.h\
 vecmath.h view.h
	mcppc -c mesh.cpp

meshaddwindow_class.o: color.h display.h iff_util.h list.h mesh.h meshaddwindow_class.cpp meshaddwindow_class.h MUIdefs.h\
 MUIutility.h object.h popup_menu.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c meshaddwindow_class.cpp

modeler.o: animtree_class.h attrswindow_class.h browsertree_class.h browser_class.h camera.h color.h color_class.h\
 cone.h csg.h display.h dispwindow_class.h draw_class.h errors.h flares.h float_class.h globalwindow_class.h\
 iff_util.h light.h list.h mainwindow_class.h materialitem_class.h material_class.h mesh.h meshaddwindow_class.h\
 modeler.cpp msghandler_class.h MUIdefs.h MUIutility.h numreq_class.h object.h picload.h popup_menu.h\
 prefs.h prefswindow_class.h preview.h project.h ray:keyfile/keyfile_lib.h renderwindow_class.h render_class.h\
 requview_class.h sci.h settings_class.h slider_class.h star.h statewindow_class.h subtask.h surface.h\
 texture.h typedefs.h undo.h utility.h vecmath.h view.h
	mcppc -c modeler.cpp

mouse.o: camera.h color.h display.h draw_class.h gfx2d.h globals.h iff_util.h list.h magic.h mainwindow_class.h\
 mesh.h mouse.cpp mouse.h MUIdefs.h MUIutility.h object.h popup_menu.h project.h sci.h surface.h typedefs.h\
 undo.h utility.h vecmath.h view.h
	mcppc -c mouse.cpp

msghandler_class.o: color.h display.h iff_util.h list.h msghandler_class.cpp msghandler_class.h MUIdefs.h MUIutility.h\
 object.h popup_menu.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c msghandler_class.cpp

MUIutility.o: color.h display.h iff_util.h list.h MUIdefs.h MUIutility.cpp MUIutility.h object.h popup_menu.h\
 prefs.h surface.h typedefs.h undo.h utility.h vecmath.h view.h
	mcppc -c MUIutility.cpp

numreq_class.o: color.h display.h iff_util.h list.h MUIdefs.h MUIutility.h numreq_class.cpp numreq_class.h\
 object.h popup_menu.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c numreq_class.cpp

object.o: box.h brush.h camera.h color.h cone.h cylinder.h display.h draw_class.h errors.h flares.h gfx2d.h\
 iff_util.h light.h list.h magic.h mesh.h MUIdefs.h object.cpp object.h objhand.h plane.h popup_menu.h\
 project.h rmod:objhand_lib.h rscn.h sci.h sphere.h star.h surface.h texture.h typedefs.h undo.h utility.h\
 vecmath.h view.h
	mcppc -c object.cpp

objhand.o: box.h brush.h camera.h color.h cone.h csg.h cylinder.h display.h errors.h flares.h iff_util.h\
 light.h list.h mesh.h MUIdefs.h object.h objhand.cpp objhand.h plane.h popup_menu.h sci.h sor.h sphere.h\
 star.h surface.h texture.h typedefs.h undo.h vecmath.h view.h
	mcppc -c objhand.cpp

plane.o: brush.h camera.h color.h display.h iff_util.h list.h magic.h MUIdefs.h object.h plane.cpp plane.h\
 popup_menu.h project.h rscn.h sci.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c plane.cpp

prefs.o: color.h display.h iff_util.h list.h MUIdefs.h MUIutility.h object.h popup_menu.h prefs.cpp\
 prefs.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c prefs.cpp

prefswindow_class.o: color.h display.h iff_util.h list.h MUIdefs.h MUIutility.h object.h popup_menu.h prefs.h prefswindow_class.cpp\
 prefswindow_class.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c prefswindow_class.cpp

preview.o: color.h display.h globals.h iff_util.h list.h MUIdefs.h object.h popup_menu.h preview.cpp preview.h\
 surface.h texture.h typedefs.h undo.h vecmath.h view.h
	mcppc -c preview.cpp

project.o: box.h camera.h color.h cone.h csg.h cylinder.h display.h errors.h globals.h iff_util.h light.h\
 list.h mesh.h MUIdefs.h object.h plane.h popup_menu.h project.cpp project.h rscn.h sor.h sphere.h surface.h\
 typedefs.h undo.h vecmath.h view.h
	mcppc -c project.cpp

renderwindow_class.o: camera.h color.h display.h globals.h iff_util.h list.h MUIdefs.h MUIutility.h object.h popup_menu.h\
 renderwindow_class.cpp renderwindow_class.h sci.h statewindow_class.h surface.h typedefs.h undo.h utility.h\
 vecmath.h view.h
	mcppc -c renderwindow_class.cpp

render_class.o: color.h display.h iff_util.h list.h MUIdefs.h MUIutility.h object.h popup_menu.h preview.h\
 render_class.cpp render_class.h subtask.h surface.h texture.h typedefs.h undo.h vecmath.h view.h
	mcppc -c render_class.cpp

requview_class.o: color.h display.h flares.h iff_util.h light.h list.h MUIdefs.h MUIutility.h object.h popup_menu.h\
 requview_class.cpp requview_class.h star.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c requview_class.cpp

sci.o: box.h brush.h camera.h color.h cone.h csg.h cylinder.h display.h globals.h iff_util.h light.h\
 list.h mesh.h mouse.h MUIdefs.h MUIutility.h object.h plane.h popup_menu.h prefs.h project.h sci.cpp\
 sci.h sor.h sphere.h surface.h texture.h typedefs.h undo.h utility.h vecmath.h view.h
	mcppc -c sci.cpp

settings_class.o: browsertree_class.h browser_class.h camera.h color.h cone.h csg.h display.h flares.h iff_util.h\
 light.h list.h mesh.h MUIdefs.h MUIutility.h object.h popup_menu.h requview_class.h settings_class.cpp\
 settings_class.h star.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c settings_class.cpp

slider_class.o: color.h display.h iff_util.h list.h MUIdefs.h MUIutility.h object.h popup_menu.h slider_class.cpp\
 slider_class.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c slider_class.cpp

sor.o: brush.h camera.h color.h display.h errors.h gfx2d.h iff_util.h list.h magic.h MUIdefs.h object.h\
 popup_menu.h project.h rscn.h sci.h sor.cpp sor.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c sor.cpp

sphere.o: brush.h camera.h color.h display.h iff_util.h list.h magic.h MUIdefs.h object.h popup_menu.h\
 project.h rscn.h sci.h sphere.cpp sphere.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c sphere.cpp

star.o: color.h display.h gfx2d.h iff_util.h light.h list.h MUIdefs.h object.h popup_menu.h rscn.h\
 star.cpp star.h surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c star.cpp

statewindow_class.o: camera.h color.h display.h dispwindow_class.h globals.h iff_util.h list.h MUIdefs.h MUIutility.h\
 object.h picload.h popup_menu.h prefs.h ray:keyfile/keyfile_lib.h statewindow_class.cpp statewindow_class.h\
 surface.h typedefs.h undo.h vecmath.h view.h
	mcppc -c statewindow_class.cpp

subtask.o: color.h display.h iff_util.h list.h MUIdefs.h object.h popup_menu.h preview.h subtask.cpp subtask.h\
 surface.h texture.h typedefs.h undo.h vecmath.h view.h
	mcppc -c subtask.cpp

surface.o: brush.h camera.h color.h display.h errors.h iff_util.h list.h MUIdefs.h object.h popup_menu.h\
 project.h rscn.h sci.h surface.cpp surface.h texture.h typedefs.h undo.h vecmath.h view.h
	mcppc -c surface.cpp

texture.o: color.h display.h iff_util.h list.h MUIdefs.h object.h popup_menu.h prefs.h project.h rscn.h\
 surface.h texture.cpp texture.h typedefs.h undo.h utility.h vecmath.h view.h
	mcppc -c texture.cpp

undo.o: color.h display.h iff_util.h list.h MUIdefs.h object.h popup_menu.h prefs.h sor.h surface.h\
 typedefs.h undo.cpp undo.h utility.h vecmath.h view.h
	mcppc -c undo.cpp

utility.o: color.h display.h iff_util.h list.h mainwindow_class.h MUIdefs.h MUIutility.h object.h popup_menu.h\
 prefs.h surface.h typedefs.h undo.h utility.cpp utility.h vecmath.h view.h
	mcppc -c utility.cpp

view.o: camera.h color.h display.h errors.h globals.h iff_util.h list.h MUIdefs.h object.h popup_menu.h\
 surface.h typedefs.h undo.h vecmath.h view.cpp view.h
	mcppc -c view.cpp

