/***************
 * PROGRAM:       Modeler
 * NAME:          popup_menu.h
 * DESCRIPTION:   definitions for popup menu
 * AUTHORS:       Andreas Heumann
 * HISTORY:
 *    DATE     NAME  COMMENT
 *    26.01.96 ah    initial release
 ***************/

#ifndef POPUP_MENU_H
#define POPUP_MENU_H

// popup menu actions
enum
{
	POP_NONE,
	POP_OBJECT_MOVE,
	POP_OBJECT_ROTATE,
	POP_OBJECT_SCALE,
	POP_WORLD_MOVE,
	POP_WORLD_ROTATE,
	POP_WORLD_SCALE,
	POP_WORLD_SETTINGS,
	POP_WORLD_RENDER,
	POP_SETTINGS,
	POP_ATTRIBUTE,
	POP_CAMERA_ACTIVE,
	POP_OBJECT2SCENE,
	POP_MATERIAL_NEW,
	POP_MATERIAL_LOAD,
	POP_MATERIAL_LOADNEW,
	POP_MATERIAL_SAVE,
	POP_MATERIAL_DELETE,
	POP_MATERIAL_PROPERTIES,
	POP_MATERIAL_ASSIGNTOSELECTED,
	POP_MATERIAL_REMOVEUNUSED,
	POP_MATERIAL_REMOVEIDENTICAL,
	POP_SPHERE,
	POP_BOX,
	POP_CYLINDER,
	POP_CONE,
	POP_SOR,
	POP_PLANE,
	POP_POINTLIGHT,
	POP_SPOTLIGHT,
	POP_DIRECTIONALLIGHT,
	POP_CAMERA,
	POP_CSG,
	POP_AXIS,
	POP_MESHSPHERE,
	POP_MESHCUBE,
	POP_MESHTUBE,
	POP_MESHCONE,
	POP_MESHPLANE,
	POP_MESHTORUS
};

#endif
