#ifndef _INCLUDE_TDDD_H
#define _INCLUDE_TDDD_H

/*
 * File generated by StormLink from SoftDisk:User/mcpp3/work/octree/module_src/objlib.fd
 * DO NOT EDIT
 * $VER: tddd 2.3 (13-Jun-99)
 */
#ifdef __cplusplus
extern "C" {
#endif
#pragma amicall(ObjHandBase, 0x1e, objInit())
#pragma amicall(ObjHandBase, 0x24, objRead())
#pragma amicall(ObjHandBase, 0x2a, objCleanup())
#ifdef __cplusplus
};
#endif
#endif
