#ifndef _INCLUDE_TGAPPC_H
#define _INCLUDE_TGAPPC_H

/*
 * File generated by StormLink from SoftDisk:User/mcpp3/work/octree/module_src/piclib.fd
 * DO NOT EDIT
 * $VER: tgappc 2.3 (09-Mai-99)
 */
#ifdef __cplusplus
extern "C" {
#endif
#pragma amicall(PicHandBase, 0x1e, picRead())
#pragma amicall(PicHandBase, 0x24, picWrite())
#ifdef __cplusplus
};
#endif
#endif
